# Numpy_Assignment_2:

## Submitted Muhammad Hassan


## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
import numpy as np
ar1D = np.array([[0, 1, 2, 3, 4,5, 6, 7, 8, 9]])
print(ar1D)

ar2D = ar1D.reshape(2, -1)
print(ar2D)


[[0 1 2 3 4 5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [20]:
ar_1 = np.arange(0,10).reshape(2,5)
ar_2 = np.repeat(1,10).reshape(2,-1)

combine_array_v = np.vstack((ar_1, ar_2))
combine_array_v

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [21]:
combine_array_h = np.hstack((ar_1, ar_2))
combine_array_h

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [33]:
arr_of_arr = np.array([[0,1],[2, 3],[4,5],[6, 7],[8,9]])
print(arr_of_arr)

print()
flat_arr = arr_of_arr.ravel()
print("Required Output")
print(flat_arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Required Output
[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [38]:
one_array = np.arange(0, 15).reshape(5,3)
print(one_array)
print()
print("Required Output")
one_array.flatten()

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Required Output


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [43]:
arr1D = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
print(arr1D)

print()
higher_dim = arr1D.reshape(5,3)
print("Required Output")
print(higher_dim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Required Output
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [46]:
arr5d = np.arange(25).reshape(5,5)
print(arr5d)
print()
print("Required Output")
sqrts = arr5d * arr5d
print(sqrts)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Required Output
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

## Question:9

### Find the standard deviation of the previous array in Q8?

## Question:10

### Find the median of the previous array in Q8?

## Question:11

### Find the transpose of the previous array in Q8?

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

## Question:13

### Find the determinant of the previous array in Q12?

## Question:14

### Find the 5th and 95th percentile of an array?

## Question:15

### How to find if a given array has any null values?