# **Assignment For Numpy**

Difficulty Level **Beginner**


Submitted by **Muhammad Hassan**

**PIAIC**  QUARTER#2

Roll No	**PIAIC182558**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
vector_1 = np.arange(10, 50)
vector_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
vector_1.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
print(type(vector_1))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print()
print(np.show_config())

1.24.1

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', Non

7. Print the dimension of the array in question 3


In [7]:
print(vector_1.ndim)

1


8. Create a boolean array with all the True values

In [16]:
bool_type = np.ones(10, dtype='bool')
bool_type

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [21]:
arr2d = np.arange(24).reshape(4,6)
print(arr2d)
print("Dimension of Array = ", arr2d.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Dimension of Array =  2


10. Create a three dimensional array



In [23]:
arr3d = np.arange(64).reshape(4,4,4)
print(arr3d)
print("Dimension of Array = ", arr3d.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]
Dimension of Array =  3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [24]:
vector_ = np.array([1,2,3,4,5])
vector_[::-1]

array([5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [25]:
tenth_null = np.zeros(10)
tenth_null[4] = 1
tenth_null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [29]:
identity_vector = np.identity(3)
identity_vector

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [32]:
arr = np.array([1, 2, 3, 4, 5],dtype='float')
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [36]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
           [7., 2., 12.]])

print("Multiplication of two arrays (arr1 and arr2) = ", arr1 * arr2)

Multiplication of two arrays (arr1 and arr2) =  [[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [39]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
resultant_array = arr1 > arr2
print(resultant_array)
print()

print(arr1<arr2)

[[ True False  True]
 [False  True False]]

[[False  True False]
 [ True False  True]]


17. Extract all odd numbers from arr with values(0-9)

In [49]:
arr = np.arange(0,10)
print(arr[arr%2!=0])

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [50]:
arr[arr%2!=0] = -1
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [51]:
arr_1 = np.arange(0,10)
arr_1[5:9] = 12
arr_1

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [69]:
arr2d = np.ones(25).reshape(5,5)
arr2d[1:-1,1:-1] = 0

arr2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [74]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[arr2d == 5] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [79]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [86]:
arr2d = np.arange(9).reshape(3,3)
first_row= arr2d[0]
print(first_row)

[0 1 2]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [88]:
arr2d = np.arange(9).reshape(3,3)
second_row= arr2d[1]
print(second_row)

[3 4 5]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [89]:
arr2d = np.arange(9).reshape(3,3)
third_row= arr2d[2]
print(third_row)

[6 7 8]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [101]:
array_10th = np.random.rand(100).reshape(10,10)

print("Shape of array = ", array_10th.shape)
print("Minimum Value is = ", array_10th.min())
print("Maximum Value is = ", array_10th.max())

Shape of array =  (10, 10)
Minimum Value is =  0.002690986282747221
Maximum Value is =  0.9805780113754005


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [103]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
com_elements = np.intersect1d(a,b)
com_elements

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [106]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
com_ele_index_match = np.where(a==b)[0]
com_ele_index_match

array([1, 3, 5, 7], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

a
Find all the values from arry **data** where the values from array **names** are not equal to **Will**


In [112]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
print("Values start where Will is not there ")
value_of_will = data[names != 'Will']
print(value_of_will)

[[-1.26510121  0.07472073  1.30724578 -0.13608403]
 [ 0.10368311 -0.11302051  2.33259503  1.21885079]
 [ 0.42918485  0.40808456  0.18291123 -1.65880488]
 [-1.61276422 -1.93086798 -0.15552797 -2.53786186]
 [-0.10210283  0.80218751 -0.80971314  0.46411748]
 [ 0.02380747 -2.61717833 -0.5848782  -0.24072902]
 [-0.45692122 -0.42603254  0.99675668  0.00681585]]
Values start where Will is not there 
[[-1.26510121  0.07472073  1.30724578 -0.13608403]
 [ 0.10368311 -0.11302051  2.33259503  1.21885079]
 [-1.61276422 -1.93086798 -0.15552797 -2.53786186]
 [ 0.02380747 -2.61717833 -0.5848782  -0.24072902]
 [-0.45692122 -0.42603254  0.99675668  0.00681585]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [118]:
filter_array = (names != "Will") & (names != "Joe")
result = data[filter_array]
print(result)

[[-1.26510121  0.07472073  1.30724578 -0.13608403]
 [-1.61276422 -1.93086798 -0.15552797 -2.53786186]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [123]:
arr2D = np.random.uniform(1,15, size=(5,3))
arr2D

array([[ 4.6736674 ,  7.2717448 ,  5.57825847],
       [14.73781296, 14.42504155,  1.09790557],
       [13.49180765,  3.52156149,  8.84847053],
       [14.62804854, 13.90748823, 11.89562256],
       [ 6.68577447,  3.5919083 ,  4.25158209]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [129]:
arr_2 = np.arange(1, 17).reshape(2,2,4)
arr_2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [135]:
swap_arr_2 = np.swapaxes(arr_2, 1,0)
swap_arr_2

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [161]:
arr_2 = np.random.rand(10)

sqr = np.sqrt(arr_2)

sqr[sqr<0.5] = 0
sqr

array([0.6937321 , 0.        , 0.        , 0.53938888, 0.7960092 ,
       0.        , 0.94464324, 0.        , 0.        , 0.50812108])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [167]:
arr1 = np.random.rand(12)
arr2 = np.random.rand(12)
# print(arr1)
# print(arr2)
max_arr = np.maximum(arr1, arr2)
max_arr

array([0.95394369, 0.92549514, 0.87652796, 0.83264659, 0.18275238,
       0.80352115, 0.41932844, 0.31820905, 0.74716281, 0.22549663,
       0.665342  , 0.66236865])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [171]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [175]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
del(b)
a

array([1, 2, 3, 4, 5])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [182]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray, 1, axis=1)
sampleArray = np.insert(sampleArray, 1, newColumn, axis=1)
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [183]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x.dot(y))

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [192]:
matrix = np.random.rand(4,5)
cumulative_sum = np.cumsum(matrix, axis=1)
cumulative_sum

array([[0.05509813, 0.27822331, 0.35182826, 1.25516328, 1.73290456],
       [0.77052479, 1.52099063, 1.52235502, 1.82379832, 2.71782126],
       [0.74550558, 1.16833597, 1.83938419, 1.91565374, 2.39476198],
       [0.216761  , 0.42273271, 0.54005648, 1.25965806, 1.79744069]])

## Done (March, 06, 2023)