# Apply Numpy 20 Universal functions 

NumPy provides several universal functions (ufuncs) that perform element-wise operations on arrays. Some common NumPy ufuncs are:

1. abs: Calculates the absolute value element-wise.

2. sqrt: Calculates the square root element-wise.

3. exp: Calculates the exponential of each element.

4. log, log10, log2: Calculates the logarithm with base e, 10, and 2, respectively.

5. sin, cos, tan: Trigonometric sine, cosine, and tangent functions.

6. sinh, cosh, tanh: Hyperbolic sine, cosine, and tangent functions.

7. floor: Rounds each element down to the nearest integer.

8. ceil: Rounds each element up to the nearest integer.

9. round: Rounds each element to the nearest integer.

10. maximum, minimum: Element-wise maximum and minimum of two arrays.

11. add, subtract, multiply, divide: Element-wise addition, subtraction, multiplication, and division.

12. power: Raises each element to a specified power.

13. mod: Element-wise modulus (remainder after division).

These functions can be applied to arrays of any shape, including scalars. To use these functions, you need to import NumPy first:

In [3]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])

In [4]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.absolute(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [11]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [12]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [13]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [14]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [18]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [19]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [20]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [21]:
np.floor(a)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
np.ceil(a)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
np.round(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.max(a)

9

In [25]:
np.min(a)

1

In [26]:
a + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
a - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7])

In [28]:
a * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [32]:
np.power(a, 2)

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [34]:
np.mod(a,2)

array([1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)