                                                 Basic Numpy Exercises 
                                               Compiled by: Dr. Noman Islam

#### 1. Generate a 1D NumPy array containing numbers from -2 to 2 in increments of 0.2. Use optional start and step arguments of np.arange() function.

In [2]:
import numpy as np

In [3]:
#one way to do this question
result = np.arange(-2, 2+0.2, 0.2)
result

array([-2.0000000e+00, -1.8000000e+00, -1.6000000e+00, -1.4000000e+00,
       -1.2000000e+00, -1.0000000e+00, -8.0000000e-01, -6.0000000e-01,
       -4.0000000e-01, -2.0000000e-01, -4.4408921e-16,  2.0000000e-01,
        4.0000000e-01,  6.0000000e-01,  8.0000000e-01,  1.0000000e+00,
        1.2000000e+00,  1.4000000e+00,  1.6000000e+00,  1.8000000e+00,
        2.0000000e+00])

In [4]:
#Another way to do this question
start = -2
stop = 2
step = 0.2
array = np.arange(start, stop + step, step)
array

array([-2.0000000e+00, -1.8000000e+00, -1.6000000e+00, -1.4000000e+00,
       -1.2000000e+00, -1.0000000e+00, -8.0000000e-01, -6.0000000e-01,
       -4.0000000e-01, -2.0000000e-01, -4.4408921e-16,  2.0000000e-01,
        4.0000000e-01,  6.0000000e-01,  8.0000000e-01,  1.0000000e+00,
        1.2000000e+00,  1.4000000e+00,  1.6000000e+00,  1.8000000e+00,
        2.0000000e+00])

#### 2. Generate another 1D NumPy array containing 11 equally spaced values between 0.5 and 1.5. Extract every second element of the array

In [5]:
#one way to do
equal11spaced = np.arange(0.5, 1.5, 11)
second_element = equal11spaced[::2]
second_element

array([0.5])

In [6]:
start = 0.5
stop = 1.5
step = 11
array = np.arange(start, stop, step)
second_ele = array[::2]
second_ele

array([0.5])

#### 3. Create a 4x4 array with arbitrary values.Extract every element from the second row.


In [7]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [8]:
#One way 
second_row = array[1, :]
second_row

array([5, 6, 7, 8])

In [9]:
#Another way with negative indexing
second_row = array[-3 , :]
second_row

array([5, 6, 7, 8])

#### 4. Extract every element from the third column

In [10]:
#Element of third columns
third_col = array[: :, 3]
third_col

array([ 4,  8, 12, 16])

#### 5. Assign a value of 0.21 to upper left 2x2 subarray.

In [14]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
array[:2, :2] = 0.21
array

array([[ 0,  0,  3,  4],
       [ 0,  0,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 6. Read an 2D array from the file exercise1_4.dat. You can usethe function np.loadtxt():
data = np.loadtxt(‘exercise1_4.dat’)

#### Split the array into four subblocks (upper left, upper right, lower left, lower right) using np.split(). Construct then the full array again with np.concatenate(). You can visualize the various arrays with matplotlib’s imshow(), i.e. import pylab pylab.imshow(data)