                                                 Basic Numpy Exercises 
                                               Compiled by: Dr. Noman Islam

#### 1. Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions.

In [3]:
import numpy as np
#one way
unif_array = np.linspace(-1.3, 2.5, 64)
unif_array

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

In [4]:
#Second way
start = -1.3
stop = 2.5
step = 64
resultant_Array = np.linspace(start, stop, step)
resultant_Array

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

#### 2. Generate an array of length  3n  filled with the cyclic pattern 1, 2, 3.

In [5]:
n = 10
pattern = np.array([1, 2, 3])
array = np.tile(pattern, n//len(pattern) + 1)[:n]
array


array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1])

In [7]:
array = np.repeat(pattern, n//len(pattern) +1)[:n]
array

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3])

#### 3. Create an array of the first 10 odd integers.

In [9]:
tenodd_num = np.arange(1, 20, 2)
tenodd_num

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
#From simple slicing
tenodd_num[:10]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

#### 4. Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [30]:
zeros_array = np.zeros((10,10))
zeros_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
array = np.zeros((10, 10))
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1
array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

This is done by assigning 1 to slices of the array, such as array[0, :] and array[-1, :], which represent the **first** and **last rows**, respectively. Similarly, array[:, 0] and array[:, -1] represent the **first and last columns**.

#### 5. Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [34]:
array = np.zeros((8, 8), dtype=int)
array[1::2, ::2] = 1
array[::2, 1::2] = 1

array

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

 The first slicing expression array[1::2, ::2] selects every second row starting from the second row (1::2), and every second column starting from the **first column** (::2). The values in these slices are then set to 1.

Similarly, the second slicing expression array[::2, 1::2] selects every second row starting from the first row (::2), and every second column starting from the second column (1::2). The values in these slices are also set to 1.