                                                 Basic Numpy Exercises 
                                               Compiled by: Dr. Noman Islam

#### Derivatives can be calculated numerically with the finite difference method as:
f'(x)=f(x+del(x)) - f(x-del(x))/2*del(x)

Construct 1D Numpy array containing the values of x in the interval [0,π/2] with spacing Δx=0.1. Evaluate numerically
the derivative of sin in this interval (excluding the end points) using the above formula. Try to avoid for loops.
Compare the result to function cos in the same interval

In [1]:
import numpy as np
x = np.arange(0, np.pi/2, 0.1)

In [2]:
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5])

In [3]:
y = np.sin(x)

In [4]:
y

array([0.        , 0.09983342, 0.19866933, 0.29552021, 0.38941834,
       0.47942554, 0.56464247, 0.64421769, 0.71735609, 0.78332691,
       0.84147098, 0.89120736, 0.93203909, 0.96355819, 0.98544973,
       0.99749499])

In [5]:
dy_dx = (np.sin(x + 0.1) - np.sin(x - 0.1)) / (2 * 0.1)

In [6]:
dy_dx

array([0.99833417, 0.99334665, 0.97843395, 0.95374506, 0.91952666,
       0.87612066, 0.82396074, 0.76356809, 0.69554611, 0.62057447,
       0.53940225, 0.45284051, 0.36175413, 0.26705322, 0.16968401,
       0.07061937])

In [7]:
cos_y = np.cos(x)

In [8]:
cos_y

array([1.        , 0.99500417, 0.98006658, 0.95533649, 0.92106099,
       0.87758256, 0.82533561, 0.76484219, 0.69670671, 0.62160997,
       0.54030231, 0.45359612, 0.36235775, 0.26749883, 0.16996714,
       0.0707372 ])

In [13]:
# Compare the result to cos(x)
print(np.allclose(dy_dx[1:-1], cos_y[1:-1]))

False
